### ISSUE TITLE
Feature Request: Way to Export Supply and Demand

### ISSUE THREAD

**Issue by Noshei** [NotNite/ReSanctuary#17]
So there are a few tools out there to help determine the best things to craft, but they require you manually input the Popularity, Supply, and Demand Shift.  It would be amazing if this plugin could provide a way to easily export that information in a table structure.

**Comment by GioPanaro** [comment]
Yes! We need this!

**Comment by MarkusWo** [comment]
I can recommend [AutoMammet](https://github.com/Rietty/AutoMammet), which has this functionality.
