### ISSUE TITLE
Map isn't properly refreshed for item location.

### ISSUE THREAD

**Issue by Kurochi51** [NotNite/ReSanctuary#21]
Everytime you click on an "Show on map" or on the item itself inside the ToDo widget, the location of the previous item doesn't get erased if you don't close the map. In the screenshot below I've clicked every item top to bottom, without closing the map in-between. Not sure if known bug, intended behaviour, or just a sol situation.
This also seems to happen if you press the same item.

![Overlapping map](https://i.imgur.com/oHm270J.png)

**Comment by NotNite** [comment]
This is intentional behavior to allow multiple items to show on the map at a time for gathering.
