### ISSUE TITLE
Todo tab doesn't have any alignment

### ISSUE THREAD

**Issue by filliph** [NotNite/ReSanctuary#4]
When viewing the Todo tab, the number input boxes are not aligned, so it's not very easy to mass-click either the - or + buttons.

![image](https://user-images.githubusercontent.com/9424286/186724237-f77b2f63-a820-40fd-837b-84c4743f0c7d.png)

Would you consider adding the number input box _before_ the icon, so it would look like
```
- [2] + <islandpalmleaf.png> Island Palm Leaf
- [2] + <Islewort.png> Islewort
```
etc, instead?

Thanks!

**Comment by NotNite** [comment]
![image](https://user-images.githubusercontent.com/44414597/186738280-a9da346f-9e6d-4d3e-acb2-2e0a580f2717.png)
