### ISSUE TITLE
Todo widget: Sort missing materials up top

### ISSUE THREAD

**Issue by filliph** [NotNite/ReSanctuary#6]
For very large todo lists, it would be helpful if it could be sorted on-the-fly such that items with missing materials would be sorted on the top.

![image](https://user-images.githubusercontent.com/9424286/186726487-aed68769-b23e-4794-84bf-1b14a1903a94.png)

I have to expand the widget quite a bit to make sure I'm not missing any materials.

**Comment by NotNite** [comment]
Done. Will commit soon.
