### ISSUE TITLE
Todo list: Number input needs a debounce before deletion

### ISSUE THREAD

**Issue by filliph** [NotNite/ReSanctuary#8]
Steps to reproduce:
1. Add an item to the Todo list and set requirement to 10
2. Try to adjust it to 20 by deleting the 1 either via backspace or delete key depending on where your cursor is
3. Item disappears from the todo list

There should be a small debounce such that it's possible to make these adjustments without immediately deleting the row.

**Comment by NotNite** [comment]
This is kind of hard to do, unfortunately - might be an ImGui limitation. Keeping open to track a workaround.

**Comment by NotNite** [comment]
Nevermind, I'm silly - found a flag. Fixing!
